// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfxmzojgpmvrmeuiskir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmeG16b2pncG12cm1ldWlza2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODQwMjMsImV4cCI6MjA3MDQ2MDAyM30.MzLCz7_f6q1dFk4pLVSFMz5wSCWDrHNfhrJMfcQuaQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});